package enums;

public enum Butt {
	EXIT,
	PAT_INTRO,ADMIN_INTRO,
	PAT_ADD,PAT_FIND_BY_ID, PAT_LIST,
	DOC_ADD,DOC_FIND_BY_ID,DOC_FIND_BY_NAME,DOC_LIST,DOC_UPDATE,DOC_DELETE,
	NUR_ADD,NUR_FIND_BY_ID,NUR_FIND_BY_NAME,NUR_LIST,NUR_UPDATE,NUR_DELETE
	;
}	
